# Generated by Django 4.1.4 on 2022-12-27 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='description',
        ),
        migrations.RemoveField(
            model_name='category',
            name='name',
        ),
        migrations.RemoveField(
            model_name='category',
            name='url',
        ),
        migrations.AddField(
            model_name='category',
            name='title',
            field=models.CharField(default=True, max_length=40, unique=True),
            preserve_default=False,
        ),
    ]
